// attached_assets/Starter_code/Angular_starter_code/src/app/core/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  standalone: true,
  selector: 'app-dashboard',
  imports: [RouterLink],
  template: `
    <div class="grid cols-2">
      <div class="card">
        <div style="font-weight:700;margin-bottom:8px">Quick Links</div>
        <div style="display:flex;gap:8px;flex-wrap:wrap">
          <a class="btn" routerLink="/policies">Policies</a>
          <a class="btn" routerLink="/claims">Claims</a>
          <a class="btn" routerLink="/customers">Customers</a>
          <a class="btn" routerLink="/underwriting">Underwriting</a>
          <a class="btn" routerLink="/reports">Reports</a>
        </div>
      </div>
      <div class="card">
        <div style="font-weight:700;margin-bottom:8px">Welcome</div>
        <p style="color:#9aa3b2">Starter template for an Insurance portal built with Angular.</p>
      </div>
    </div>
  `
})
export class DashboardComponent {}

// attached_assets/Starter_code/React_starter_code/src/pages/Dashboard.jsx
import { Link } from 'react-router-dom';
import ReportChart from '../components/ReportChart.jsx';

const chartData = [
  { month: 'Jan', claims: 12, premiums: 40 },
  { month: 'Feb', claims: 16, premiums: 42 },
  { month: 'Mar', claims: 10, premiums: 45 },
  { month: 'Apr', claims: 20, premiums: 44 },
  { month: 'May', claims: 18, premiums: 47 },
  { month: 'Jun', claims: 14, premiums: 50 }
];

export default function Dashboard() {
  return (
    <div className="grid cols-2">
      <div className="card">
        <div style={{ fontWeight: 700, marginBottom: 8 }}>Quick Links</div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          <Link className="btn" to="/policies">View Policies</Link>
          <Link className="btn" to="/claims">Manage Claims</Link>
          <Link className="btn" to="/customers">Customers</Link>
          <Link className="btn" to="/underwriting">Underwriting</Link>
          <Link className="btn" to="/reports">Reports</Link>
        </div>
      </div>
      <ReportChart data={chartData} />
    </div>
  );
}
