// attached_assets/Starter_code/React_native_starter_code/src/screens/Dashboard.tsx
import React from 'react';
import { View, Text, Button, ScrollView } from 'react-native';

export default function Dashboard({ navigation }: any) {
  return (
    <ScrollView contentContainerStyle={{ padding: 16 }}>
      <View style={{ backgroundColor: '#121a2e', borderRadius: 12, padding: 16, marginBottom: 16 }}>
        <Text style={{ fontWeight: '700', color: '#e6e8ef', marginBottom: 8 }}>Quick Links</Text>
        <View style={{ gap: 8 }}>
          <Button title="Policies" onPress={() => navigation.navigate('Policies')} />
          <Button title="Claims" onPress={() => navigation.navigate('Claims')} />
          <Button title="Customers" onPress={() => navigation.navigate('Customers')} />
          <Button title="Underwriting" onPress={() => navigation.navigate('Underwriting')} />
          <Button title="Reports" onPress={() => navigation.navigate('Reports')} />
        </View>
      </View>
      <View style={{ backgroundColor: '#121a2e', borderRadius: 12, padding: 16 }}>
        <Text style={{ fontWeight: '700', color: '#e6e8ef', marginBottom: 8 }}>Welcome</Text>
        <Text style={{ color: '#9aa3b2' }}>Starter template for an Insurance portal built with React Native.</Text>
      </View>
    </ScrollView>
  );
}

// attached_assets/Starter_code/Angular_starter_code/src/app/core/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  standalone: true,
  selector: 'app-dashboard',
  imports: [RouterLink],
  template: `
    <div class="grid cols-2">
      <div class="card">
        <div style="font-weight:700;margin-bottom:8px">Quick Links</div>
        <div style="display:flex;gap:8px;flex-wrap:wrap">
          <a class="btn" routerLink="/policies">Policies</a>
          <a class="btn" routerLink="/claims">Claims</a>
          <a class="btn" routerLink="/customers">Customers</a>
          <a class="btn" routerLink="/underwriting">Underwriting</a>
          <a class="btn" routerLink="/reports">Reports</a>
        </div>
      </div>
      <div class="card">
        <div style="font-weight:700;margin-bottom:8px">Welcome</div>
        <p style="color:#9aa3b2">Starter template for an Insurance portal built with Angular.</p>
      </div>
    </div>
  `
})
export class DashboardComponent {}
